" source $VIMRUNTIME/defaults.vim

set showcmd
set whichwrap+=h,l,<,>,[,],b,s
set scrolloff=3

" matching/search options
set ignorecase
set smartcase
set incsearch

" easy exit from insert mode
inoremap jk <Esc>
inoremap kj <Esc>

syntax on
filetype plugin indent on
colorscheme peachpuff

autocmd FileType gitcommit colorscheme pablo
autocmd FileType gitcommit set spell
autocmd FileType gitcommit set spelllang=en
autocmd FileType gitcommit highlight clear SpellBad
autocmd FileType gitcommit highlight SpellBad ctermfg=darkred cterm=underline
autocmd FileType gitcommit highlight clear SpellCap
autocmd FileType gitcommit highlight SpellCap ctermfg=darkblue

autocmd FileType gitrebase colorscheme elflord

" better soft wrap
set wrap
set linebreak " don't break in the middle of a word
let &showbreak = '﬌ ' " wrapped line marker
set breakindent " visually indent wrapped lines

" no tabs
:set expandtab
:set tabstop=4
:set shiftwidth=4

" don't put x-deleted chars in any register
nnoremap x "_x
vnoremap x "_x

" on wrapped lines, move cursor by display line instead of physical line
noremap <silent> k gk
noremap <silent> j gj
noremap <silent> 0 g0
noremap <silent> $ g$
