" source $VIMRUNTIME/defaults.vim

set showcmd
set mouse=a
set whichwrap+=<,>,[,]
set scrolloff=3

" matching/search options
set ignorecase
set smartcase
set incsearch

syntax on
filetype plugin indent on
colorscheme peachpuff

autocmd FileType gitcommit startinsert
autocmd FileType gitcommit colorscheme pablo
autocmd FileType gitcommit set spell
autocmd FileType gitcommit set spelllang=en
autocmd FileType gitcommit highlight clear SpellBad
autocmd FileType gitcommit highlight SpellBad ctermfg=darkred cterm=underline
autocmd FileType gitcommit highlight clear SpellCap
autocmd FileType gitcommit highlight SpellCap ctermfg=darkblue

autocmd FileType gitrebase colorscheme elflord
