# Dotbot config file

- defaults:
    link:
      relink: true

- link:
    ~/.zshrc: zshrc
    ~/.oh-my-zsh/custom.symlink: ohmyzsh-custom
    ~/.p10k.zsh: p10k.zsh

- shell:
    - git submodule update --depth 1
