### plugins config

export ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$ZSH/custom.symlink"

ZSH_THEME="powerlevel10k/powerlevel10k"

CASE_SENSITIVE="true" # for completion

HIST_STAMPS="%d/%m %H:%M"

# every Oh My Zsh setting:
# https://github.com/ohmyzsh/ohmyzsh/blob/master/templates/zshrc.zsh-template

plugins=(
  z
  bgnotify
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


### my config

bindkey -v # viins (vi INSERT) keymap
export KEYTIMEOUT=10 # reduce delay on mode changes

bindkey -v '^R' history-incremental-search-backward # ctrl+R to search history
bindkey -v '^S' history-incremental-search-forward # ctrl+S to reverse search
bindkey -v '^U' kill-whole-line # ctrl+U to discard line
bindkey -v 'jk' vi-cmd-mode # jk/kj to escape to Normal mode
bindkey -v 'kj' vi-cmd-mode

# revert unwanted default set by OMZ
unset LESS

alias gitp='GIT_PAGER="less -FRX" git'

type pbcopy &> /dev/null || alias pbcopy='xsel --clipboard --input'
type pbpaste &> /dev/null || alias pbpaste='xsel --clipboard --output'
pb() {
    # if fd 0 (stdin) not a terminal (so a pipe); then copy; else paste
    [[ ! -t 0 ]] && pbcopy || pbpaste
}

# vi-yank also copies to pasteboard
vi-yank-pbcopy() {
    zle vi-yank
    echo "$CUTBUFFER" | pbcopy
}
zle -N vi-yank-pbcopy
bindkey -M vicmd 'y' vi-yank-pbcopy

alias vscode="$(which code)"
alias code='cd code'

alias ls='ls --color=tty --group-directories-first'

# prompt before removing files
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'

# don't clear scrollback/history
alias clear='clear -x'

# interactive-only features of pyenv
[[ -d "$HOME/.pyenv" ]] && eval "$(pyenv init -)"
