### plugins config

export ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$ZSH/custom.symlink"

ZSH_THEME="powerlevel10k/powerlevel10k"

CASE_SENSITIVE="true" # for completion

HIST_STAMPS="%d/%m %H:%M"

# every Oh My Zsh setting:
# https://github.com/ohmyzsh/ohmyzsh/blob/master/templates/zshrc.zsh-template

plugins=(
  z
  bgnotify
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


### my config

bindkey -v # viins (vi INSERT) keymap
bindkey -v 'jk' vi-cmd-mode # jk/kj to escape to Normal mode
bindkey -v 'kj' vi-cmd-mode
export KEYTIMEOUT=20 # reduce delay on mode changes

bindkey -v '^R' history-incremental-search-backward # ctrl+R to search history
bindkey -v '^S' history-incremental-search-forward # ctrl+S to reverse search
bindkey -v '^U' kill-whole-line # ctrl+U to discard line
bindkey -v '\e.' insert-last-word # alt+. to insert last arg from previous command

# interactive-only features of pyenv
[[ -d "$HOME/.pyenv" ]] && eval "$(pyenv init -)"

source tweaks.sh
source utils.sh
