### plugins config

export ZSH="$HOME/.oh-my-zsh"
ZSH_CUSTOM="$ZSH/custom.symlink"

ZSH_THEME="powerlevel10k/powerlevel10k"

CASE_SENSITIVE="true" # for completion

HIST_STAMPS="%d/%m %H:%M"

# every Oh My Zsh setting:
# https://github.com/ohmyzsh/ohmyzsh/blob/master/templates/zshrc.zsh-template

plugins=(
  z
  bgnotify
  zsh-autosuggestions
  zsh-syntax-highlighting
  my-patches
)

source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


### my config

bindkey -v

unset LESS
alias gitp='GIT_PAGER="less -FRX" git'

type pbcopy &> /dev/null || alias pbcopy='xsel --clipboard --input'
type pbpaste &> /dev/null || alias pbpaste='xsel --clipboard --output'

alias vscode="$(which code)"
alias code='cd code'

alias ls='ls --color=tty --group-directories-first'

# prompt before removing files
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -I'

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# version manager for Java, Scala, sbt, etc.
export SDKMAN_DIR="/home/victor-gp/.sdkman"
[[ -s "/home/victor-gp/.sdkman/bin/sdkman-init.sh" ]] && source "/home/victor-gp/.sdkman/bin/sdkman-init.sh"
